/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package site.soroosh.schema;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class InflightState extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4404394863471315788L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"InflightState\",\"namespace\":\"site.soroosh.schema\",\"fields\":[{\"name\":\"inflightRequestId\",\"type\":\"string\"},{\"name\":\"pendingRequestIds\",\"type\":{\"type\":\"array\",\"items\":\"string\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<InflightState> ENCODER =
      new BinaryMessageEncoder<InflightState>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<InflightState> DECODER =
      new BinaryMessageDecoder<InflightState>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<InflightState> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<InflightState> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<InflightState> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<InflightState>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this InflightState to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a InflightState from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a InflightState instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static InflightState fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence inflightRequestId;
   private java.util.List<java.lang.CharSequence> pendingRequestIds;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public InflightState() {}

  /**
   * All-args constructor.
   * @param inflightRequestId The new value for inflightRequestId
   * @param pendingRequestIds The new value for pendingRequestIds
   */
  public InflightState(java.lang.CharSequence inflightRequestId, java.util.List<java.lang.CharSequence> pendingRequestIds) {
    this.inflightRequestId = inflightRequestId;
    this.pendingRequestIds = pendingRequestIds;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return inflightRequestId;
    case 1: return pendingRequestIds;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: inflightRequestId = (java.lang.CharSequence)value$; break;
    case 1: pendingRequestIds = (java.util.List<java.lang.CharSequence>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'inflightRequestId' field.
   * @return The value of the 'inflightRequestId' field.
   */
  public java.lang.CharSequence getInflightRequestId() {
    return inflightRequestId;
  }


  /**
   * Sets the value of the 'inflightRequestId' field.
   * @param value the value to set.
   */
  public void setInflightRequestId(java.lang.CharSequence value) {
    this.inflightRequestId = value;
  }

  /**
   * Gets the value of the 'pendingRequestIds' field.
   * @return The value of the 'pendingRequestIds' field.
   */
  public java.util.List<java.lang.CharSequence> getPendingRequestIds() {
    return pendingRequestIds;
  }


  /**
   * Sets the value of the 'pendingRequestIds' field.
   * @param value the value to set.
   */
  public void setPendingRequestIds(java.util.List<java.lang.CharSequence> value) {
    this.pendingRequestIds = value;
  }

  /**
   * Creates a new InflightState RecordBuilder.
   * @return A new InflightState RecordBuilder
   */
  public static site.soroosh.schema.InflightState.Builder newBuilder() {
    return new site.soroosh.schema.InflightState.Builder();
  }

  /**
   * Creates a new InflightState RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new InflightState RecordBuilder
   */
  public static site.soroosh.schema.InflightState.Builder newBuilder(site.soroosh.schema.InflightState.Builder other) {
    if (other == null) {
      return new site.soroosh.schema.InflightState.Builder();
    } else {
      return new site.soroosh.schema.InflightState.Builder(other);
    }
  }

  /**
   * Creates a new InflightState RecordBuilder by copying an existing InflightState instance.
   * @param other The existing instance to copy.
   * @return A new InflightState RecordBuilder
   */
  public static site.soroosh.schema.InflightState.Builder newBuilder(site.soroosh.schema.InflightState other) {
    if (other == null) {
      return new site.soroosh.schema.InflightState.Builder();
    } else {
      return new site.soroosh.schema.InflightState.Builder(other);
    }
  }

  /**
   * RecordBuilder for InflightState instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<InflightState>
    implements org.apache.avro.data.RecordBuilder<InflightState> {

    private java.lang.CharSequence inflightRequestId;
    private java.util.List<java.lang.CharSequence> pendingRequestIds;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(site.soroosh.schema.InflightState.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.inflightRequestId)) {
        this.inflightRequestId = data().deepCopy(fields()[0].schema(), other.inflightRequestId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.pendingRequestIds)) {
        this.pendingRequestIds = data().deepCopy(fields()[1].schema(), other.pendingRequestIds);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing InflightState instance
     * @param other The existing instance to copy.
     */
    private Builder(site.soroosh.schema.InflightState other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.inflightRequestId)) {
        this.inflightRequestId = data().deepCopy(fields()[0].schema(), other.inflightRequestId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.pendingRequestIds)) {
        this.pendingRequestIds = data().deepCopy(fields()[1].schema(), other.pendingRequestIds);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'inflightRequestId' field.
      * @return The value.
      */
    public java.lang.CharSequence getInflightRequestId() {
      return inflightRequestId;
    }


    /**
      * Sets the value of the 'inflightRequestId' field.
      * @param value The value of 'inflightRequestId'.
      * @return This builder.
      */
    public site.soroosh.schema.InflightState.Builder setInflightRequestId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.inflightRequestId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'inflightRequestId' field has been set.
      * @return True if the 'inflightRequestId' field has been set, false otherwise.
      */
    public boolean hasInflightRequestId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'inflightRequestId' field.
      * @return This builder.
      */
    public site.soroosh.schema.InflightState.Builder clearInflightRequestId() {
      inflightRequestId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'pendingRequestIds' field.
      * @return The value.
      */
    public java.util.List<java.lang.CharSequence> getPendingRequestIds() {
      return pendingRequestIds;
    }


    /**
      * Sets the value of the 'pendingRequestIds' field.
      * @param value The value of 'pendingRequestIds'.
      * @return This builder.
      */
    public site.soroosh.schema.InflightState.Builder setPendingRequestIds(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[1], value);
      this.pendingRequestIds = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'pendingRequestIds' field has been set.
      * @return True if the 'pendingRequestIds' field has been set, false otherwise.
      */
    public boolean hasPendingRequestIds() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'pendingRequestIds' field.
      * @return This builder.
      */
    public site.soroosh.schema.InflightState.Builder clearPendingRequestIds() {
      pendingRequestIds = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public InflightState build() {
      try {
        InflightState record = new InflightState();
        record.inflightRequestId = fieldSetFlags()[0] ? this.inflightRequestId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.pendingRequestIds = fieldSetFlags()[1] ? this.pendingRequestIds : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<InflightState>
    WRITER$ = (org.apache.avro.io.DatumWriter<InflightState>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<InflightState>
    READER$ = (org.apache.avro.io.DatumReader<InflightState>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.inflightRequestId);

    long size0 = this.pendingRequestIds.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (java.lang.CharSequence e0: this.pendingRequestIds) {
      actualSize0++;
      out.startItem();
      out.writeString(e0);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.inflightRequestId = in.readString(this.inflightRequestId instanceof Utf8 ? (Utf8)this.inflightRequestId : null);

      long size0 = in.readArrayStart();
      java.util.List<java.lang.CharSequence> a0 = this.pendingRequestIds;
      if (a0 == null) {
        a0 = new SpecificData.Array<java.lang.CharSequence>((int)size0, SCHEMA$.getField("pendingRequestIds").schema());
        this.pendingRequestIds = a0;
      } else a0.clear();
      SpecificData.Array<java.lang.CharSequence> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          java.lang.CharSequence e0 = (ga0 != null ? ga0.peek() : null);
          e0 = in.readString(e0 instanceof Utf8 ? (Utf8)e0 : null);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.inflightRequestId = in.readString(this.inflightRequestId instanceof Utf8 ? (Utf8)this.inflightRequestId : null);
          break;

        case 1:
          long size0 = in.readArrayStart();
          java.util.List<java.lang.CharSequence> a0 = this.pendingRequestIds;
          if (a0 == null) {
            a0 = new SpecificData.Array<java.lang.CharSequence>((int)size0, SCHEMA$.getField("pendingRequestIds").schema());
            this.pendingRequestIds = a0;
          } else a0.clear();
          SpecificData.Array<java.lang.CharSequence> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              java.lang.CharSequence e0 = (ga0 != null ? ga0.peek() : null);
              e0 = in.readString(e0 instanceof Utf8 ? (Utf8)e0 : null);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










