/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package site.soroosh.schema;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class LoanResult extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6796843519596481726L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"LoanResult\",\"namespace\":\"site.soroosh.schema\",\"fields\":[{\"name\":\"requestId\",\"type\":\"string\"},{\"name\":\"result\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<LoanResult> ENCODER =
      new BinaryMessageEncoder<LoanResult>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<LoanResult> DECODER =
      new BinaryMessageDecoder<LoanResult>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<LoanResult> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<LoanResult> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<LoanResult> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<LoanResult>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this LoanResult to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a LoanResult from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a LoanResult instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static LoanResult fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence requestId;
   private java.lang.CharSequence result;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public LoanResult() {}

  /**
   * All-args constructor.
   * @param requestId The new value for requestId
   * @param result The new value for result
   */
  public LoanResult(java.lang.CharSequence requestId, java.lang.CharSequence result) {
    this.requestId = requestId;
    this.result = result;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return requestId;
    case 1: return result;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: requestId = (java.lang.CharSequence)value$; break;
    case 1: result = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'requestId' field.
   * @return The value of the 'requestId' field.
   */
  public java.lang.CharSequence getRequestId() {
    return requestId;
  }


  /**
   * Sets the value of the 'requestId' field.
   * @param value the value to set.
   */
  public void setRequestId(java.lang.CharSequence value) {
    this.requestId = value;
  }

  /**
   * Gets the value of the 'result' field.
   * @return The value of the 'result' field.
   */
  public java.lang.CharSequence getResult() {
    return result;
  }


  /**
   * Sets the value of the 'result' field.
   * @param value the value to set.
   */
  public void setResult(java.lang.CharSequence value) {
    this.result = value;
  }

  /**
   * Creates a new LoanResult RecordBuilder.
   * @return A new LoanResult RecordBuilder
   */
  public static site.soroosh.schema.LoanResult.Builder newBuilder() {
    return new site.soroosh.schema.LoanResult.Builder();
  }

  /**
   * Creates a new LoanResult RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new LoanResult RecordBuilder
   */
  public static site.soroosh.schema.LoanResult.Builder newBuilder(site.soroosh.schema.LoanResult.Builder other) {
    if (other == null) {
      return new site.soroosh.schema.LoanResult.Builder();
    } else {
      return new site.soroosh.schema.LoanResult.Builder(other);
    }
  }

  /**
   * Creates a new LoanResult RecordBuilder by copying an existing LoanResult instance.
   * @param other The existing instance to copy.
   * @return A new LoanResult RecordBuilder
   */
  public static site.soroosh.schema.LoanResult.Builder newBuilder(site.soroosh.schema.LoanResult other) {
    if (other == null) {
      return new site.soroosh.schema.LoanResult.Builder();
    } else {
      return new site.soroosh.schema.LoanResult.Builder(other);
    }
  }

  /**
   * RecordBuilder for LoanResult instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<LoanResult>
    implements org.apache.avro.data.RecordBuilder<LoanResult> {

    private java.lang.CharSequence requestId;
    private java.lang.CharSequence result;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(site.soroosh.schema.LoanResult.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.requestId)) {
        this.requestId = data().deepCopy(fields()[0].schema(), other.requestId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.result)) {
        this.result = data().deepCopy(fields()[1].schema(), other.result);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing LoanResult instance
     * @param other The existing instance to copy.
     */
    private Builder(site.soroosh.schema.LoanResult other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.requestId)) {
        this.requestId = data().deepCopy(fields()[0].schema(), other.requestId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.result)) {
        this.result = data().deepCopy(fields()[1].schema(), other.result);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'requestId' field.
      * @return The value.
      */
    public java.lang.CharSequence getRequestId() {
      return requestId;
    }


    /**
      * Sets the value of the 'requestId' field.
      * @param value The value of 'requestId'.
      * @return This builder.
      */
    public site.soroosh.schema.LoanResult.Builder setRequestId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.requestId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'requestId' field has been set.
      * @return True if the 'requestId' field has been set, false otherwise.
      */
    public boolean hasRequestId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'requestId' field.
      * @return This builder.
      */
    public site.soroosh.schema.LoanResult.Builder clearRequestId() {
      requestId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'result' field.
      * @return The value.
      */
    public java.lang.CharSequence getResult() {
      return result;
    }


    /**
      * Sets the value of the 'result' field.
      * @param value The value of 'result'.
      * @return This builder.
      */
    public site.soroosh.schema.LoanResult.Builder setResult(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.result = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'result' field has been set.
      * @return True if the 'result' field has been set, false otherwise.
      */
    public boolean hasResult() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'result' field.
      * @return This builder.
      */
    public site.soroosh.schema.LoanResult.Builder clearResult() {
      result = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public LoanResult build() {
      try {
        LoanResult record = new LoanResult();
        record.requestId = fieldSetFlags()[0] ? this.requestId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.result = fieldSetFlags()[1] ? this.result : (java.lang.CharSequence) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<LoanResult>
    WRITER$ = (org.apache.avro.io.DatumWriter<LoanResult>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<LoanResult>
    READER$ = (org.apache.avro.io.DatumReader<LoanResult>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.requestId);

    out.writeString(this.result);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.requestId = in.readString(this.requestId instanceof Utf8 ? (Utf8)this.requestId : null);

      this.result = in.readString(this.result instanceof Utf8 ? (Utf8)this.result : null);

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.requestId = in.readString(this.requestId instanceof Utf8 ? (Utf8)this.requestId : null);
          break;

        case 1:
          this.result = in.readString(this.result instanceof Utf8 ? (Utf8)this.result : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










